### ISSUE TITLE
bold, italics, underline tags

### ISSUE THREAD

**Issue by mitchcapper** [moyuyc/html-markdown#1]
Are you fine with adding these? They map pretty directly to MD but are not in the library as it is.  If so I can do a PR if you like.

**Comment by imcuttle** [comment]
thanks for your issue. bold text(`<strong>`) is translated as `**text**`, italics text(`<em>`) is translated as `*text*`, however, underline text don't have its own html tag.  so underline text can't be translated to MD directly.

**Please use cheerio branch (latest), *NOT* master.**

**Comment by mitchcapper** [comment]
Sorry I was referring to the `<b>, <i>, and <u>`.  They are not as big in HTML 5 however still sources use them.

**Comment by imcuttle** [comment]
Well, The issue was fixed in version 1.0.17.
